[project]
name = "promohunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.11.0",
    "pydantic>=2.12.1",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
]
